### ISSUE TITLE
[Feat]: Group API 생성

### ISSUE THREAD

**Issue by gr-KIM** [ZOGAKZIP-4team/BE#1]
## ✏️Description
Group API 생성

## To-Do List
- [ ] 그룹 등록
- [ ] 그룹 목록 조회
- [ ] 그룹 수정
- [ ] 그룹 삭제
- [ ] 그룹 상세 정보 조회
- [ ] 그룹 조회 권한 확인
- [ ] 그룹 공감하기
- [ ] 그룹 공개 여부 확인

**Comment by gr-KIM** [comment]
브랜치 꼬여서 새로 팝니다..ㅜㅜ
