### ISSUE TITLE
[FEAT]: Group API 생성

### ISSUE THREAD

**Issue by gr-KIM** [ZOGAKZIP-4team/BE#3]
## ✏️Description
Group API 생성

## To-Do List
- [x] 그룹 등록
- [x] 그룹 목록 조회
- [x] 그룹 수정
- [x] 그룹 삭제
- [x] 그룹 상세 정보 조회
- [x] 그룹 조회 권한 확인
- [x] 그룹 공감하기
- [x] 그룹 공개 여부 확인
